### PR TITLE
Fix short URL feature

### LINKED ISSUE #532: Fix short URL copying to clipboard
### Describe the Bug
Currently, the short URL is copied to the clipboard on the server (`pyperclip` module), see function `copy_short_url()` in `src/cms/views/pages/page_actions.py`.

### Expected Behavior
Users in the Web GUI should be able to copy the short URL to the clipboard. We need a JavaScript function in the page view or pages list that copies the short URL into the clipboard in the browser. The `copy_short_url()` function can probably be dropped.

Example for copying to clipboard in JavaScript: https://www.w3schools.com/howto/howto_js_copy_clipboard.asp

### PR DESCRIPTION
**Pull request by svenseeberg**
- Copying the short URL to the clipboard was done on the back end, not in the browser.
- Remove short UUID dependency

Fixes: #532 
Fixes: #533

### CODE REVIEW

File: src/cms/static/js/pages/page_bulk_actions.js [hunk 1]
```diff
@@ -31,3 +31,14 @@ function bulk_action_execute() {
...
+function short_url_to_clipboard(url) {
+    u('#mirrored_page_first_div').removeClass('hidden');
+    var copyText = document.getElementById("copy_to_clipboard");
+    copyText.value = "https://" + location.hostname + "/" + url;
+    u('#copy_to_clipboard').removeClass('hidden');
+    copyText.select();
+    copyText.setSelectionRange(0, 99999);
+    document.execCommand("copy");
+    u('#copy_to_clipboard').addClass('hidden');
+}
```
Comment (svenseeberg) [inline src/cms/static/js/pages/page_bulk_actions.js:44]: This code currently exists twice. Have not yet found a place where to put it in order to merge it.

File: src/cms/templates/pages/page_tree_node.html [hunk 2]
```diff
@@ -103,7 +103,7 @@
             {% endif %}
         {% endif %}
         {% if page_translation %}
-        <a href="{% url 'copy_short_url' page_id=page.id region_slug=region.slug language_code=language.code %}" title="{% trans 'Copy short link' %}" class="py-3 px-2">
+        <a href="#" onclick="short_url_to_clipboard('{{ page_translation.short_url }}');" title="{% trans 'Copy short link' %}" class="py-3 px-2">
```
Comment (svenseeberg) [inline src/cms/templates/pages/page_tree_node.html:106]: I think this needs to go away from the page list, because the user cannot directly choose the translation for the URL.

File: src/cms/static/js/pages/page_bulk_actions.js (hunk 1 above)
Comment (timoludwig) [reply src/cms/static/js/pages/page_bulk_actions.js:44]: I started to separate the js files by tasks in `src/cms/static/js/pages/`, so you could just create a new file `src/cms/static/js/pages/copy_to_clipboard.js` and include this in the page tree template...

File: src/cms/templates/pages/page_tree_node.html (hunk 2 above)
Comment (timoludwig) [reply src/cms/templates/pages/page_tree_node.html:106]: Once we fix the language switcher, it will no longer be a problem to change e.g. to the english page tree and export the short url from there...

File: src/cms/views/pages/page_actions.py [hunk 3]
```diff
@@ -112,46 +111,23 @@ def delete_page(request, page_id, region_slug, language_code):
...
-            _("URL '{}' was successfully copied to clipboard.".format(short_url)),
-        )
-    # pylint: disable=broad-except
-    except Exception as e:
-        logger.exception(e)
-        messages.warning(
-            request,
-            _("URL '{}' could not be copied to clipboard.".format(short_url)),
-        )
+    queryset = PageTranslation.objects.filter(short_url_id=short_url_id)
```
Comment (svenseeberg) [inline src/cms/views/pages/page_actions.py:118]: Needs a check if a page is published.

File: src/cms/views/pages/page_actions.py [hunk 4]
```diff
@@ -112,46 +111,23 @@ def delete_page(request, page_id, region_slug, language_code):
...
-@login_required
-def expand_short_url(request, short_url_id):
+def expand_page_translation_id(request, short_url_id):
     """
-    Searches for a page with requested short_url_id and redirects to that page.
+    Searches for a page translation with corresponding ID and redirects browser to web app
     """
-    queryset = PageTranslation.objects.filter(short_url_id=short_url_id)
-    page_translation = queryset.first()
+    page_translation = PageTranslation.objects.get(id=short_url_id)
```
Comment (svenseeberg) [inline src/cms/views/pages/page_actions.py:130]: Needs a check if a page is published.

File: src/cms/static/js/pages/page_bulk_actions.js (hunk 1 above)
Comment (svenseeberg) [reply src/cms/static/js/pages/page_bulk_actions.js]: I modified the function to be used in other cases as well and moved it into a dedicted JS file.

File: src/cms/templates/pages/page_tree_node.html (hunk 2 above)
Comment (svenseeberg) [reply src/cms/templates/pages/page_tree_node.html]: Alright.

File: src/cms/views/pages/page_actions.py (hunk 4 above)
Comment (timoludwig) [reply src/cms/views/pages/page_actions.py:130]: Also, there might be a newer revision of the page translation...
And we have to think about what to do on a 404... would we show the 404 of the cms, or redirect to the 404 in the webapp?

File: src/cms/views/pages/page_actions.py [hunk 5]
```diff
@@ -112,48 +111,25 @@ def delete_page(request, page_id, region_slug, language_code):
...
+    page_translation = queryset.first()
 
-    return redirect(
-        "pages",
-        **{
-            "region_slug": region_slug,
-            "language_code": language_code,
-        },
-    )
+    if page_translation and page_translation.latest_public_revision:
```
Comment (svenseeberg) [inline src/cms/views/pages/page_actions.py:121]: @timoludwig do we need to additionally check for archived pages here? I guess yes?

Comment (timoludwig) [reply src/cms/views/pages/page_actions.py:121]: Yes, exactly.

Comment (svenseeberg) [reply src/cms/views/pages/page_actions.py]: Alright then :)

File: src/cms/views/pages/page_actions.py (hunk 4 above)
Comment (svenseeberg) [reply src/cms/views/pages/page_actions.py:134]: Okay, we actually should redirect to the newest version (slug), for sure. About the 404: good question.

File: src/cms/views/pages/page_actions.py [hunk 6]
```diff
@@ -112,48 +111,33 @@ def delete_page(request, page_id, region_slug, language_code):
...
-        "pages",
-        **{
-            "region_slug": region_slug,
-            "language_code": language_code,
-        },
-    )
+    if (
+        page_translation
+        and page_translation.latest_public_revision
+        and page_translation.page.archived == False
```
Comment (timoludwig) [inline src/cms/views/pages/page_actions.py:124]: I think pylint wants to see this:
```suggestion
        and not page_translation.page.archived
```

File: src/cms/views/pages/page_actions.py [hunk 7]
```diff
@@ -112,48 +111,33 @@ def delete_page(request, page_id, region_slug, language_code):
...
     """
-    queryset = PageTranslation.objects.filter(short_url_id=short_url_id)
-    page_translation = queryset.first()
+    page_translation = PageTranslation.objects.get(id=short_url_id)
 
-    if page_translation:
+    if (
+        page_translation
+        and page_translation.latest_public_revision
+        and page_translation.page.archived == False
```
Comment (timoludwig) [inline src/cms/views/pages/page_actions.py:139]:
```suggestion
        and not page_translation.page.archived
```

File: setup.py [hunk 8]
```diff
@@ -42,6 +42,7 @@
         "rules",
         "six",
         "webauthn",
+        "shortuuid",
```
Comment (timoludwig) [inline setup.py:45]:
```suggestion
```
We can drop this now, right?

File: src/cms/views/pages/page_actions.py (hunk 4 above)
Comment (timoludwig) [reply src/cms/views/pages/page_actions.py:134]: I think the webapp has no generic 404 page, if we redirect e.g. to https://integreat.app/@@redux-first-router/NOT_FOUND, it shows `NetworkError when attempting to fetch resource.` which is a bit misleading. And when we redirect to https://integreat.app/404, it says `Sorry, but this city could not be found.`, which is also not entirely correct. So I propose to keep it as it is and show the error message of the cms...

File: setup.py (hunk 8 above)
Comment (svenseeberg) [reply setup.py]: True. I missed this line.

File: src/cms/views/pages/page_actions.py (hunk 4 above)
Comment (svenseeberg) [reply src/cms/views/pages/page_actions.py]: I'm now redirecting to the latest public revision. Should do the trick, right?

Comment (svenseeberg) [reply src/cms/views/pages/page_actions.py]: In this case the check is not required anymore :roll_eyes:

**Review by timoludwig — APPROVED** [review]
:rocket: :tada:
